### ISSUE TITLE
Newlines, quotes, escape characters, etc in strings?

### ISSUE THREAD

**Issue by kccqzy** [p-ranav/pprint#1]
I'm not sure what's the intended behavior, but this library doesn't seem to do anything special to handle quotes or newlines or other "special" characters within strings.

```
int main() {
  pprint::PrettyPrinter printer;
  printer.print("x'x\"x");
  printer.print("x\nx\nx");
}
```

It produces just the contents of the string with quotes. Is this intended behavior?

**Comment by p-ranav** [comment]
At the moment, yes. For strings, ```pprint``` does nothing more than what ```std::cout``` would do. Double quotes are added for strings and single quotes are added for characters if you call ```printer.quotes(true)```

I suggest using [fmt](https://github.com/fmtlib/fmt) for all your string formatting needs.
